var quotes = [
	'Gravy',
	'Groovy',
	'Arctic',
	'Cosmic',
	'Raspberry',
	'Twisty',
	'Scrumptious',
	'Energetic',
	'Happy',
	'Suspicious',
	'Undercover',
	'Elementary',
	'Media',
	'Roving',
	'Seasick',
	'Guatemalan',
	'Gusty',
	'Suspicious',
	'Oily',
	'Venerable',
	'Prolific',
	'Sleepy',
	'Jogging',
	'Sprinting',
	'Covert',
	'Oratorical',
	'Seismic',
	'Oleaginous',
	'Palaeolithic',
	'Postmodern',
	'Jurassic',
	'Existential',
	'Bitcoin',
	'Loose',
	'Slapstick',
	'Creative',
	'Wobbly',
	'Artistic',
	'Cauliflower',
	'Raging',
	'Screaming',
	'Basildon',
	'Mankini',
	'Rollercoaster',
	'Parachuting',
	'Hang gliding',
	'Hairy',
	'Fruity',
	'Oxygenated',
	'Welding',
]

function newQuote() {
	var randomNumber = Math.floor(Math.random() *(quotes.length));
	document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}
